package com.orderdetail.model;

import java.sql.Connection;
import java.util.List;
import java.util.Set;

public interface OrderdetailDAO_interface {

	public void insert(OrderdetailVO orderdetailVO);
	public void update(OrderdetailVO orderdetailVO);
	public void delete(String ord_id, String prod_id);
	public OrderdetailVO findByPrimaryKey(String ord_id, String prod_id);
	public List<OrderdetailVO> getAll();

	// new method
	// 此區塊與晴帆insertWithCon()相同
	public void insertByAutoGeneratedKey(OrderdetailVO orderdetailVO, Connection con);
	// 此區塊與晴帆insertWithCon()相同
	// new method
	
	// Adding by Sylvie
	// OrderlistDAO 內建有相同方法，getOrderdetailsByOrd_id(String ord_id)
	public Set<OrderdetailVO> findProductsByOrdId(String ord_id);
	// OrderlistDAO 內建有相同方法，getOrderdetailsByOrd_id(String ord_id)
	public void insertWithCon(OrderdetailVO orderdetailVO, Connection con);
}